import { describe, expect, it } from "vitest";
import { commitMessageBody, findAiAttribution } from "./ai-attribution.mjs";

describe("findAiAttribution", () => {
  it("flags a co-author trailer from an AI model", () => {
    const text = "feat: x\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>";
    expect(findAiAttribution(text)).toEqual([
      { line: 3, text: "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>" },
    ]);
  });

  it("flags co-author trailers from other AI tools, in any case", () => {
    expect(findAiAttribution("Co-authored-by: GitHub Copilot <copilot@github.com>")).toHaveLength(1);
    expect(findAiAttribution("co-authored-by: Cursor Agent <cursoragent@cursor.com>")).toHaveLength(1);
    expect(findAiAttribution("Co-Authored-By: Codex <noreply@openai.com>")).toHaveLength(1);
  });

  it("flags session links and session trailers", () => {
    expect(findAiAttribution("Claude-Session: https://claude.ai/code/session_01ABC")).toHaveLength(1);
    expect(findAiAttribution("See https://claude.ai/code/session_01ABC for details")).toHaveLength(1);
  });

  it("flags 'generated with' footers from AI tools", () => {
    expect(findAiAttribution("🤖 Generated with [Claude Code](https://claude.com/claude-code)")).toHaveLength(1);
    expect(findAiAttribution("Generated by ChatGPT")).toHaveLength(1);
    expect(findAiAttribution("_Generated by [Claude Code](https://claude.ai/code)_")).toHaveLength(1);
  });

  it("accepts a human co-author", () => {
    expect(findAiAttribution("feat: x\n\nCo-Authored-By: Ana Pérez <ana@example.com>")).toEqual([]);
  });

  it("accepts prose that talks about AI tools", () => {
    const body = [
      "## Qué cambia",
      "Claude Code no lee los AGENTS.md de subcarpetas cuando hay un CLAUDE.md en la raíz.",
      "El hook rechaza las líneas Co-Authored-By de un modelo y los pies del tipo Generated with.",
      "Ver https://code.claude.com/docs/en/memory",
    ].join("\n");
    expect(findAiAttribution(body)).toEqual([]);
  });

  it("handles empty input", () => {
    expect(findAiAttribution("")).toEqual([]);
    expect(findAiAttribution(undefined)).toEqual([]);
  });
});

describe("commitMessageBody", () => {
  it("drops git comment lines and everything below the scissors line", () => {
    const raw = [
      "feat: x",
      "",
      "# Please enter the commit message for your changes.",
      "# ------------------------ >8 ------------------------",
      "diff --git a/f b/f",
      "+Co-Authored-By: Claude <noreply@anthropic.com>",
    ].join("\n");
    expect(commitMessageBody(raw)).toBe("feat: x\n");
  });
});
